// <auto-generated />
namespace StarBlogs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _916migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_916migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201509160527463_9.16migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
